name: ci
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  testCopy:  # will create a pr to copy a file
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync test
        uses: ./
        with:
          dst-repository: 'solubris/insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git push -d origin insync
