name: ci
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  testCopy:  # will create a pr to copy a file
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync test
        uses: ./
        with:
          dst-repository: 'solubris/insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore
      - name: checkout insync-dst
        uses: actions/checkout@v2
        with:
          repository: 'solubris/insync-dst'
          path: 'insync-dst'
      - name: remove the branch created during test
        run: |
          git push -d origin insync
