name: ci
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync test
        uses: ${{ github.action_path }}/
        with:
          dst-repository: 'solubris/insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: |
            .gitignore
            .editorconfig
          dry-run: true
