name: ci
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  testFileRemoval:  # will create a pr to remove a file
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync test
        uses: ./
        with:
          dst-repository: 'solubris/insync' # push back to itself
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          dst-branch: test
          files: onlyInDst.txt
          dry-run: true
