name: ci
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  testUpdate:  # will create a pr to update existing file
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync
        uses: ./
        with:
          repository: 'insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore
          pr-branch: testUpdate
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git push -d origin testUpdate
  testCopy:  # will create a pr to copy over a new file
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync
        uses: ./
        with:
          repository: 'insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .editorconfig
          pr-branch: testCopy
      - name: check the files exist in the dst repo
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git checkout testCopy
          ls .editorconfig
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git push -d origin testCopy
  testDelete:  # will create a pr to delete file from dst
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync
        uses: ./
        with:
          repository: 'insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .dummyFileForTest
          pr-branch: testDelete
      - name: check the file does not exist in the dst repo
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git checkout testDelete
          if [ -e .dummyFileForTest ]; then
            echo .dummyFileForTest was not deleted
            exit 1
          fi
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git push -d origin testDelete
  testUpdateWithExistingBranch:  # will update existing branch/pr
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync
        uses: ./
        with:
          repository: 'insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore
          pr-branch: testUpdateWithExistingBranch
      - name: sync
        uses: ./
        with:
          repository: 'insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore .dummyFileForTest
          pr-branch: testUpdateWithExistingBranch
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git push -d origin testUpdateWithExistingBranch
  testUpdateDir:  # will create a pr to update existing file
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync
        uses: ./
        with:
          repository: 'insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: src
          pr-branch: testUpdateDir
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git push -d origin testUpdateDir
  testCopyWithSubdir:  # will create a pr to copy over a new file and creating the subdir's
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync
        uses: ./
        with:
          repository: 'insync-dst'
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: src/main/sh/run.sh
          pr-branch: testCopyWithSubdir
      - name: check the files exist in the dst repo
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git checkout testCopyWithSubdir
          ls src/main/sh/run.sh
      - name: remove the branch created during test
        run: |
          DST_PATH="$(mktemp -d /tmp/insync-dst.XXXXXX)"
          cd "$DST_PATH"
          git clone "https://${{ secrets.INSYNC_DST_TOKEN }}:x-oauth-basic@github.com/solubris/insync-dst.git" .
          git push -d origin testCopyWithSubdir
