name: ci
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
      - name: sync test
        uses: ./
        with:
          dst-repository: 'solubris/insync' # push back to itself
          dst-token: ${{ secrets.INSYNC_DST_TOKEN }}
          files: .gitignore
          dry-run: true
